### ISSUE TITLE
Game won't launch

### ISSUE THREAD

**Issue by NULLProtogen** [SheerSt/pokewilds#113]
Current version: 0.8.3

When ever I launch pokemon-wilds.exe the game starts briefly but closes half a second later.

I tried looking for people that had similar issues.

I tried rebooting.

I checked the Discord but I can't chat in any of the channels.

**Comment by NULLProtogen** [comment]
Looks like it's an audio issue. Any suggestions on a fix?

AL lib: (EE) DoReset: Failed to initialize audio client: 0x8889000a
[LwjglApplication] Couldn't initialize audio, disabling audio
org.lwjgl.openal.OpenALException: Invalid Device
        at org.lwjgl.openal.Util.checkALCError(Util.java:55)
        at org.lwjgl.openal.ALC10.alcCreateContext(ALC10.java:251)
        at org.lwjgl.openal.AL.init(AL.java:173)
        at org.lwjgl.openal.AL.create(AL.java:143)
        at org.lwjgl.openal.AL.create(AL.java:102)
        at org.lwjgl.openal.AL.create(AL.java:206)
        at com.badlogic.gdx.backends.lwjgl.audio.OpenALLwjglAudio.<init>(OpenALLwjglAudio.java:72)
        at com.badlogic.gdx.backends.lwjgl.LwjglApplication.createAudio(LwjglApplication.java:282)
        at com.badlogic.gdx.backends.lwjgl.LwjglApplication.<init>(LwjglApplication.java:90)
        at com.badlogic.gdx.backends.lwjgl.LwjglApplication.<init>(LwjglApplication.java:71)
        at com.pkmngen.game.desktop.DesktopLauncher.main(DesktopLauncher.java:20)
Exception in thread "LWJGL Application" java.lang.NullPointerException
        at com.pkmngen.game.util.LinkedMusic.<init>(LinkedMusic.java:60)
        at com.pkmngen.game.Battle.<init>(Battle.java:4375)
        at com.pkmngen.game.Game.create(Game.java:270)
        at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:150)
        at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:127)

**Comment by fourlastor** [comment]
@NULLProtogen could you try updating to the latest [release](https://github.com/SheerSt/pokewilds/releases/latest)?
