### ISSUE TITLE
Endless loop when generating a new region

### ISSUE THREAD

**Issue by crxyne** [SheerSt/pokewilds#242]
Went out to generate a new region, luckily was in dev mode testing stuff and got this stacktrace:
```
java.lang.IllegalArgumentException: bound must be positive
	at java.base/java.util.Random.nextInt(Unknown Source)
	at com.pkmngen.game.GenIsland1.<init>(GenForest2.java:2313)
	at com.pkmngen.game.GenerateWorld$1.run(PkmnMap.java:9327)
	at java.base/java.lang.Thread.run(Unknown Source)
```
From there it's an endless loop and doesn't seem to generate anything any further.

**Comment by OMMorticia** [comment]
bumping this! The Problem was in v0.8.6 and continues in v0.8.7; can't progress to any new areas on any map sizes via flying or surfing

I then built a "bridge" and began surfing from there (right on the line to the new area). Somehow this has worked and I loaded in the new place. Only differences were the bridge of ground and the fact it was day time.
