### ISSUE TITLE
Building on a map-generated structure causes save to be unloadable

### ISSUE THREAD

**Issue by riley-turben** [SheerSt/pokewilds#31]
I found a large building that had been randomly generated as part of my map. I used my Machop's build ability and was able to delete one of the roof tiles by building a chimney over top of it, and now my save file will not load the map. I've attached a copy of my save file here: [Test.sav.backup.zip](https://github.com/SheerSt/pokemon-wilds/files/7707817/Test.sav.backup.zip)

Here is the error message when I attempt to start the save up:

```
com.badlogic.gdx.utils.GdxRuntimeException: Couldn't load file: tiles/buildings/pkmnmansion_roof_Echimney.png
	at com.badlogic.gdx.graphics.Pixmap.<init>(Pixmap.java:165)
	at com.badlogic.gdx.graphics.TextureData$Factory.loadFromFile(TextureData.java:98)
	at com.badlogic.gdx.graphics.Texture.<init>(Texture.java:122)
	at com.badlogic.gdx.graphics.Texture.<init>(Texture.java:114)
	at com.pkmngen.game.util.TextureCache.get(TextureCache.java:142)
	at com.pkmngen.game.Tile.init(Tile.java:2624)
	at com.pkmngen.game.Tile.<init>(Tile.java:408)
	at com.pkmngen.game.Tile.get(Tile.java:385)
	at com.pkmngen.game.PkmnMap.loadMapFromFile(PkmnMap.java:4897)
	at com.pkmngen.game.PkmnMap.loadFromFile(PkmnMap.java:5165)
	at com.pkmngen.game.DrawSetupMenu.step(Action.java:2468)
	at com.pkmngen.game.Game.render(Game.java:1400)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:232)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:127)
Caused by: com.badlogic.gdx.utils.GdxRuntimeException: File not found: tiles/buildings/pkmnmansion_roof_Echimney.png (Internal)
	at com.badlogic.gdx.files.FileHandle.read(FileHandle.java:142)
	at com.badlogic.gdx.files.FileHandle.readBytes(FileHandle.java:228)
	at com.badlogic.gdx.graphics.Pixmap.<init>(Pixmap.java:162)
	... 13 more
AL lib: (EE) alc_cleanup: 1 device
```

**Comment by SheerSt** [comment]
Hi there @riley-turben - sorry for not seeing this sooner. I didn't have any issue loading that save file attached. The `<game-name>.sav.backup` file contains your second-to-last save - you could try loading that save file as a workaround:
 - Rename `<game-name>.sav.backup` to `<new-game-name>.sav.zip` and extract contents
 - Extracted contents need to be a directory called `<new-game-name>.sav/` with game, map0,0 etc files inside
 - Load the file.

Another potential workaround is to create a dummy png file at pokemon-wilds/mods/tiles/buildings/pkmnmansion_roof_Echimney.png in the game's directory.

If you want to zip and attach your save directory here (the directory ending in .sav instead of .sav.backup) I can also fix it for you.

**Comment by riley-turben** [comment]
Thanks for the instructions, that recovered my save! I'll attach a zipped version of the .sav directory here.
[Test.sav 2.zip](https://github.com/SheerSt/pokemon-wilds/files/7713471/Test.sav.2.zip)

**Comment by SheerSt** [comment]
@riley-turben Here is a fixed version of Test.sav.2.zip, in case you need it.

[Test.sav.zip](https://github.com/SheerSt/pokemon-wilds/files/7714236/Test.sav.zip)

**Comment by fourlastor** [comment]
Closing this as outdated
