### ISSUE TITLE
[Feature Request]: RetroPie port

### ISSUE THREAD

**Issue by Enqueued** [SheerSt/pokewilds#458]
### What would you like to request?

Hello,
I attempted to run the game with my PiBoy DMG that uses a raspberry pi 4.
I pulled the latest release, pulled the jdk, and faced with the same error that others have seen with GLFW_PLATFORM_UNAVAILABLE.

```
[LWJGL] GLFW_PLATFORM_UNAVAILABLE error
        Description : Failed to detect any supported platform
        Stacktrace  :
                org.lwjgl.glfw.GLFW.glfwInit(GLFW.java:1047)
                com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.initializeGlfw(Lwjgl3Application.java:88)
                com.badlogic.gdx.backends.lwjgl3.Lwjgl3ApplicationConfiguration.getDisplayMode(Lwjgl3ApplicationConfiguration.java:219)
                com.pkmngen.game.desktop.DesktopLauncher.getScale(DesktopLauncher.java:166)
                com.pkmngen.game.desktop.DesktopLauncher.main(DesktopLauncher.java:32)
Exception in thread "main" com.badlogic.gdx.utils.GdxRuntimeException: Unable to initialize GLFW
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.initializeGlfw(Lwjgl3Application.java:89)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3ApplicationConfiguration.getDisplayMode(Lwjgl3ApplicationConfiguration.java:219)
        at com.pkmngen.game.desktop.DesktopLauncher.getScale(DesktopLauncher.java:166)
        at com.pkmngen.game.desktop.DesktopLauncher.main(DesktopLauncher.java:32)
```

I saw that this was looked at previously in a ticket but it seems to be a few months old. Is there any update on this?

I really want to play this on my PiBoy as I dont have much time to play games on my PC and really want o try this game out after seeing it in a video.

**Comment by coco875** [comment]
> ### What would you like to request?
> 
> Hello,
> 
> I attempted to run the game with my PiBoy DMG that uses a raspberry pi 4.
> 
> I pulled the latest release, pulled the jdk, and faced with the same error that others have seen with GLFW_PLATFORM_UNAVAILABLE.
> 
> 
> 
> ```
> 
> [LWJGL] GLFW_PLATFORM_UNAVAILABLE error
> 
>         Description : Failed to detect any supported platform
> 
>         Stacktrace  :
> 
>                 org.lwjgl.glfw.GLFW.glfwInit(GLFW.java:1047)
> 
>                 com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.initializeGlfw(Lwjgl3Application.java:88)
> 
>                 com.badlogic.gdx.backends.lwjgl3.Lwjgl3ApplicationConfiguration.getDisplayMode(Lwjgl3ApplicationConfiguration.java:219)
> 
>                 com.pkmngen.game.desktop.DesktopLauncher.getScale(DesktopLauncher.java:166)
> 
>                 com.pkmngen.game.desktop.DesktopLauncher.main(DesktopLauncher.java:32)
> 
> Exception in thread "main" com.badlogic.gdx.utils.GdxRuntimeException: Unable to initialize GLFW
> 
>         at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.initializeGlfw(Lwjgl3Application.java:89)
> 
>         at com.badlogic.gdx.backends.lwjgl3.Lwjgl3ApplicationConfiguration.getDisplayMode(Lwjgl3ApplicationConfiguration.java:219)
> 
>         at com.pkmngen.game.desktop.DesktopLauncher.getScale(DesktopLauncher.java:166)
> 
>         at com.pkmngen.game.desktop.DesktopLauncher.main(DesktopLauncher.java:32)
> 
> ```
> 
> 
> 
> I saw that this was looked at previously in a ticket but it seems to be a few months old. Is there any update on this?
> 
> 
> 
> I really want to play this on my PiBoy as I dont have much time to play games on my PC and really want o try this game out after seeing it in a video.

It look like you don't have opengl drivers installed or pokewild don't support this environment 

https://www.glfw.org/docs/3.4/group__errors.html#ga3608c6c29ab7a72f3bf019f4c3a2563d
