### ISSUE TITLE
Compiling

### ISSUE THREAD

**Issue by mjKosmic** [SheerSt/pokewilds#82]
I'm trying to port this to ArkOS running on Anbernic's RG351MP but there are not compiling instructions in the README. How do i build this :)

**Comment by fourlastor** [comment]
@mjKosmic ArkOS is based on linux as far as I understood, could you try downloading the [latest release](https://github.com/SheerSt/pokewilds/releases/latest), otherplatform version?
You'll need to install a java distribution that works on ArkOS on your device (so aarm64 as far as I understood), you could try with one of the ones from https://adoptium.net/temurin/releases, or using [SDKMAN](https://sdkman.io/) to let it install the correct version for you

After that, you should be able to play by using the `linux-launcher` script

In the future we might have more architectures covered for the native linux distribution (aarm64 is the next target we would like to cover for Linux), which would eliminate the need to install java, so be sure to check for updates every now and then!

**Comment by SillyFerretFuzz** [comment]
I have attempted this with the rg353v, using ArkOS's preinstalled java, and with openjdk java 13 (arm64).

Both encounter this error:
```
ark@rg353v:/roms2/ports/pokewilds$ java -jar pokewilds.jar
Save path: /roms2/ports/pokewilds
[LWJGL] GLFW_PLATFORM_UNAVAILABLE error
        Description : Failed to detect any supported platform
        Stacktrace  :
                org.lwjgl.glfw.GLFW.glfwInit(GLFW.java:1047)
                com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.initializeGlfw(Lwjgl3Application.java:88)
                com.badlogic.gdx.backends.lwjgl3.Lwjgl3ApplicationConfiguration.getDisplayMode(Lwjgl3ApplicationConfiguration.java:219)
                com.pkmngen.game.desktop.DesktopLauncher.getScale(DesktopLauncher.java:104)
                com.pkmngen.game.desktop.DesktopLauncher.main(DesktopLauncher.java:18)
Exception in thread "main" com.badlogic.gdx.utils.GdxRuntimeException: Unable to initialize GLFW
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.initializeGlfw(Lwjgl3Application.java:89)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3ApplicationConfiguration.getDisplayMode(Lwjgl3ApplicationConfiguration.java:219)
        at com.pkmngen.game.desktop.DesktopLauncher.getScale(DesktopLauncher.java:104)
        at com.pkmngen.game.desktop.DesktopLauncher.main(DesktopLauncher.java:18)
```



Update: This appears to be LWJGL not finding or not recognizing the window managing environment? Trying to work that out

Update 2: ArkOS only has GBM, which won't allow for a window like the jar wants. I don't know enough to continue right now.

**Comment by fourlastor** [comment]
@SillyFerretFuzz you could try running it with `java -jar pokewilds.jar angle_gles20`, I'm not sure if there's a way to run it otherwise given that error

**Comment by SillyFerretFuzz** [comment]
That command resulted in the same error :(

It appears GLFW does not support any method of rendering to a buffer without use of a running window system:

[GLFW doesn't support creating contexts without an associated window. However, contexts with hidden windows can be created with the (GLFW_VISIBLE) window hint.](https://www.glfw.org/docs/latest/context.html#context_offscreen)

There was also discussion in [this thread](https://github.com/glfw/glfw/issues/648)

As the OS only supports GBM I can't find any way to run the game headless. I've been trying to hack together solutions but I don't think it's possible the way GLFW is configured.

**Comment by fourlastor** [comment]
Yeah, I don't think it's possible to get around this limitation unfortunately

**Comment by JeodC** [comment]
AmberELEC / uOS / Jelos has JDK support already built in once you start a j2me game for the first time, but you also need a display backend for your java application. So just running a jar file without anything won't work.

Any alternative display methods possible? LIBGDX maybe?
