### ISSUE TITLE
Stuck Generating New Terrain

### ISSUE THREAD

**Issue by Kingkai81** [SheerSt/pokewilds#88]
I used Charizard to fly straight up until I reached a world border. It gave me the prompt to continue and if I did, itd have to generate new terrain. I have now been Generating for the past 25 min. And I haven't saved in a long time. 
![16583134542021427908332214509220](https://user-images.githubusercontent.com/109664136/179962329-5763da6d-7a3e-4d70-bf0e-d1a022be4c9a.jpg)

**Comment by Aromede** [comment]
+1

Got the exact same issue. The save is "corrupted", when I try to load it's just the background playing indefinitely. I can move, it prompt's the "Going further will take you to a new area" message, but if I say "No" it just keeps asking, and if I say "Yes" it goes back to a plain background of sky (night stars or blue sky clouds).

I know dev has a lot to work on but they might want to look at it faster because bugs corrupting saves are the worst (you have to start everything over).

**Comment by Aromede** [comment]
So I went into dev mode to try to take a screenshot of the map by pressing "L" but it prompted this error. The game can't find a proper location in map0,-1as if I was stuck in the loading screen of the generating area between map0,0 and map0,-1. Replacing the bugged map0,-1 with the map0,0 and renaming it map0,-1 doesn't help either.

Java version infor info
1.8.0_292rporation
1.8phics processor info/PCIe/SSE2
Graphics processor info
NVIDIA Corporation 3060/PCIe/SSE2
NVIDIA GeForce RTX 3060/PCIe/SSE2
OpenGL infoA 516.59
4.6.0 NVIDIA 516.59.interiorTilesIndex
this.nickname
ivysauraticGame.map.interiorTilesIndex
Game.staticGame.map.interiorTilesIndex
100s.interiorIndex
this.interiorIndex
100s.nicknameme.map.interiorTilesIndex
this.nickname
dratiniaticGame.map.interiorTilesIndex
Game.staticGame.map.interiorTilesIndex
100s.interiorIndex
this.interiorIndex
100s.nicknameme.map.interiorTilesIndex
this.nickname
skarmoryticGame.map.interiorTilesIndex
Game.staticGame.map.interiorTilesIndex
100s.interiorIndex
this.interiorIndex
100s.nicknameme.map.interiorTilesIndex
this.nickname
charmeleoncGame.map.interiorTilesIndex
Game.staticGame.map.interiorTilesIndex
100s.interiorIndex
this.interiorIndex
100s.nicknameme.map.interiorTilesIndex
this.nickname
machoptaticGame.map.interiorTilesIndex
Game.staticGame.map.interiorTilesIndex
100s.interiorIndex
this.interiorIndex
100s.nicknameme.map.interiorTilesIndex
this.nickname
wartortleicGame.map.interiorTilesIndex
Game.staticGame.map.interiorTilesIndex
100s.interiorIndex
this.interiorIndex
100d dungeons
used dungeons
desert_ruins1r spawn from file
mansion1yer.spawnLoc
regi1ng player spawn from file
Loading player spawn from file
game.player.spawnLoc
(-496.0,-3104.0)nIndexading new area
game.player.spawnIndex
100ion stack before loading new areaessor
com.badlogic.gdx.utils.GdxRuntimeException: Couldn't load file: Difaulte.sav/map0,-1.png
map_5000at com.badlogic.gdx.graphics.Pixmap.<init>(Pixmap.java:165)
map_142 at com.pkmngen.game.PkmnMap.loadMapFromFile(PkmnMap.java:5035)
map_140 at com.pkmngen.game.PkmnMap.loadFromFile(PkmnMap.java:5165)
map_130 at com.pkmngen.game.DrawSetupMenu.step(Action.java:2468)
map_120 at com.pkmngen.game.Game.render(Game.java:1400)
map_115 at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:232)
map_110 at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:127)
Caused by: java.io.IOException: Error loading pixmap: Corrupt PNG
map_108 at com.badlogic.gdx.graphics.g2d.Gdx2DPixmap.<init>(Gdx2DPixmap.java:85)
map_0  cat com.badlogic.gdx.graphics.Pixmap.<init>(Pixmap.java:163)
map_0  c... 6 more.game.Player$Flyingirements
Creating screenshot of full map...
Exception in thread "LWJGL Application" java.lang.NullPointerException
map_0  cat com.pkmngen.game.Game.handleDebuggingInput(Game.java:740)
Found exat com.pkmngen.game.Game.render(Game.java:1152)rBinder".
map0,0 Dat com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:232)
Backing at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:127)
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Saving game to file...
Done.ops
Found mods for: giblenteriorTilesIndex
this.nickname
dusclopseriorIndex
Game.staticGame.map.interiorTilesIndex
100s.nickname
this.interiorIndex
97me.staticGame.map.interiorTilesIndex
this.nickname
dusclopseriorIndex
Game.staticGame.map.interiorTilesIndex
100s.nickname
this.interiorIndex
97me.staticGame.map.interiorTilesIndex
this.nickname
dusclopseriorIndex
Game.staticGame.map.interiorTilesIndex
100nd mods for: pikachu
this.interiorIndex
96sclops
Found mods for: pikachueriorTilesIndex
this.nickname
dusclopseriorIndex
Game.staticGame.map.interiorTilesIndex
100s.nickname
this.interiorIndex
97me.staticGame.map.interiorTilesIndex
this.nickname
dusclopseriorIndex
Game.staticGame.map.interiorTilesIndex
100s.nickname
this.interiorIndex
96me.staticGame.map.interiorTilesIndex
this.nickname
dusclopseriorIndex
Game.staticGame.map.interiorTilesIndex
100ding player spawn from file
this.interiorIndexoc
96496.0,-3104.0)
Loading player spawn from file
game.player.spawnLoc
(-496.0,-3104.0)
game.player.spawnIndex
100


Then I tried reinstalling the entire game and replace the game file in the .sav folder with the old bugged one. Nothing new happened, the game still puts me in this grey area. See screenshot for a better idea of the issue.

![pokewilds_stuck](https://user-images.githubusercontent.com/110646078/183220750-0c388e15-fb1a-42d3-b1f8-dc46c9849420.PNG)

Maybe if we can have access to the game file in the .sav folder we can try editing the position of the character to put on the map0,0 but I don't know if we can edit this file (it doesn't even have an extension).
